### ISSUE TITLE
JavaScript errors on sub-pages

### ISSUE THREAD

**Issue by opdavies** [jcarouth/devbookclub.org#3]
On the live site, on any page other than the homepage, there are a number of JavaScript errors that are preventing the Bootstrap dropdown menu from working. In fact, it looks like jQuery isn't found at all.

![screenshot 2015-08-10 19 50 04](https://cloud.githubusercontent.com/assets/339813/9180269/48ddd83c-3f99-11e5-94e3-a59bfa96f12b.png)

When I clone the repository locally, and run `sculpin update` and `sculpin generate --server --watch` it works on all pages, which suggests that it's an issue with the version of the code checked out on the server?

**Comment by opdavies** [comment]
Actually, I just found one place where the jQuery URL could be updated, and I've added a PR at https://github.com/jcarouth/devbookclub.org/pull/4.

It still all works locally for me though.

**Comment by jcarouth** [comment]
Thanks for the PR. That resolved this problem.
